version: '3.9'
services:
  database:
    container_name: database
    build:
      context: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root@123"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/todo_list"
      SPRING_DATASOURCE_USERNAME: "todo_user"
      SPRING_DATASOURCE_PASSWORD: "user@123"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend