version: '3.9'
services:
  database:
    container_name: database
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: "root@123"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    container_name: backend
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/todo_list"
      SPRING_DATASOURCE_USERNAME: "todo_user"
      SPRING_DATASOURCE_PASSWORD: "user@123"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy

  apigateway:
    container_name: apigateway
    build:
      context: ./gateway
    ports:
      - 82:80
    environment:
      BACKEND_URL: "backend:5000"
      # Base64 encoded value of basic auth credentials set in backend application.properties
      # echo -n "admin:admin@123" | base64
      BASIC_AUTH_CREDENTIALS: "YWRtaW46YWRtaW5AMTIz"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      backend:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 81:80
    depends_on:
      apigateway:
        condition: service_healthy