db:
  replicaCount: 1

  image:
    name: to-do-db
    pullPolicy: Never
    tag: latest

  service:
    type: ClusterIP
    port: 3306
    protocol: TCP
    targetPort: 3306

  resources: {}

  livenessProbe:
    exec:
      command:
        - sh
        - -c
        - "mysqladmin ping -h localhost || exit 1"
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3

  readinessProbe:
    exec:
      command:
        - sh
        - -c
        - "mysqladmin ping -h localhost || exit 1"
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3