apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: three-tier-app-fr
spec:
  selector:
    matchLabels:
      app: three-tier-app-fr
  replicas: {{ .Values.fr.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: three-tier-app-fr
    spec:
      containers:
      - name: three-tier-app-frontend
        image: to-do-fr:latest
        imagePullPolicy: Never
{{- if .Values.fr.resources }}
        resources:
{{ toYaml .Values.fr.resources | indent 12 }}
{{- end }}
        ports:
        - containerPort: 80
          name:  frontend-port
      restartPolicy: Always