apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: three-tier-app-gw
  type: {{ .Values.gw.service.type | default "ClusterIP" }}
  ports:
  - name: gateway-service-port
    protocol: {{ .Values.gw.service.protocol | default "TCP" }}
    port: {{ .Values.gw.service.port | default 80 }}
    targetPort: {{ .Values.gw.service.targetPort | default .Values.gw.containerPortName | default 80 }}